import type { Company } from "./types";

export const COMPANIES: Company[] = [
  {
    id: "utility",
    name: "Georgia Grid Services",
    industry: "Utility field services · 340 employees",
    nowMin: 390,
    sources: [
      { name: "ADP Workforce Now", meta: "HR · 340 records", node: 0 },
      { name: "IBM Maximo", meta: "Assets · 12,410 WOs", node: 1 },
      { name: "OSIsoft PI", meta: "SCADA historian · live", node: 2 },
      { name: "Oracle EBS", meta: "ERP · 96k rows", node: 5 },
      { name: "Outage Mgmt System", meta: "OMS · live", node: 8 },
      { name: "SharePoint", meta: "Docs · 4,120 files", node: 3 },
    ],
    kpis: [
      { label: "OPEN WORK ORDERS", val: "142", color: "#14181C" },
      { label: "CREWS ON SITE", val: "11 / 14", color: "#14181C" },
      { label: "COMPLIANCE FLAGS", val: "3", color: "#B47614" },
      { label: "DATA FRESHNESS", val: "2 min", color: "#15854F" },
    ],
    alerts: [
      { sev: "CRITICAL", color: "#C7452F", at: 372, time: "06:12", title: "Transformer T-114 running +8°C over seasonal norm", detail: "PI historian trend crossed threshold. Same signature preceded the T-109 failure last August.", loc: "Substation 4 · Bay 1", q: "What do I do about T-114?" },
      { sev: "WARNING", color: "#B47614", at: 340, time: "05:40", title: "Thursday crew shortage on Feeder 12 rebuild", detail: "6 PTO approvals in ADP overlap the 4-crew minimum on Maximo WO-2291. You will be two crews short.", loc: "Ops · scheduling", q: "Fix Thursday’s crew shortage" },
      { sev: "WARNING", color: "#B47614", at: 0, time: "Mon", title: "OSHA 300 log missing 2 March incidents", detail: "Incident reports exist in SharePoint but were never posted to the log. Citable gap if audited.", loc: "Compliance", q: "Close the OSHA log gap" },
    ],
    intro: "Overnight read: 6 systems, 214,000 rows reconciled. Three things need you today.\n\n1. T-114 is trending toward the same failure signature as T-109 last August.\n2. Thursday's Feeder 12 job is two crews short because of approved PTO.\n3. Your OSHA 300 log is missing two March incidents that exist in SharePoint.\n\nWhere do you want to start?",
    suggestions: ["What do I do about T-114?", "Fix Thursday’s crew shortage", "Close the OSHA log gap"],
    replies: [
      { text: "T-114, in order:\n\n1. Dispatch a thermal inspection today — crew 7 is already at Substation 4 until 15:00 (Maximo), so no extra roll.\n2. Shift non-critical load to T-115, which is at 61% capacity (PI).\n3. If the trend holds past 92°C, pre-stage the spare from the Macon yard — that's what cut the outage from 3 days to 6 hours on T-109.\n\nI've drafted the work order. Want me to file it?", cites: ["PI historian · T-114 trend", "Maximo · crew 7 schedule", "Incident file · T-109, Aug ’25"] },
      { text: "Thursday, two options:\n\nA. Crews 3 and 9 are on a deferrable maintenance ticket (WO-2307, no compliance deadline) — move them to Feeder 12.\nB. Approved contractor pool has 4 qualified linemen available Thursday at standard rate.\n\nOption A costs nothing and delays a low-risk ticket 4 days. I'd take A. Want the schedule change drafted for your sign-off?", cites: ["ADP · PTO approvals", "Maximo · WO-2291, WO-2307"] },
      { text: "The two missing incidents are documented in SharePoint (IR-031, IR-034, both March, both recordable under 29 CFR 1904). I've pre-filled the OSHA 300 entries from the incident reports — they need a supervisor signature, nothing else.\n\nOnce posted, your log is current and the audit trail shows the correction was self-identified. That matters if OSHA ever looks.", cites: ["SharePoint · IR-031, IR-034", "29 CFR 1904.29"] },
    ],
    action: { title: "Snapshot ready for regional director", desc: "One-pager: T-114 risk, the plan, and cost of inaction — drafted from today’s data. Send it before the 10:00 standup." },
    plan: {
      subtitle: "What to do next, in order — grounded in today’s data, not a template.",
      why: "T-114 is sequenced first because failure cost dwarfs everything else; the crew fix rides on a no-cost schedule swap that expires Wednesday; the OSHA correction is cheap now and expensive after an audit letter.",
      cols: [
        { title: "NOW · TODAY", color: "#C7452F", items: [{ t: "Thermal inspection on T-114", d: "Crew 7 is on site until 15:00 — zero extra roll cost.", tag: "PREVENTS OUTAGE" }, { t: "Move crews 3 & 9 to Feeder 12", d: "Deferrable ticket WO-2307 slips 4 days, no penalty.", tag: "NO-COST FIX" }] },
        { title: "NEXT · THIS WEEK", color: "#B47614", items: [{ t: "Post the 2 missing OSHA 300 entries", d: "Pre-filled from SharePoint incident reports. Needs one signature.", tag: "COMPLIANCE" }, { t: "Pre-stage spare transformer at Macon", d: "Only if T-114 trend passes 92°C. Decision point: Thursday.", tag: "CONTINGENCY" }] },
        { title: "LATER · THIS QUARTER", color: "#15854F", items: [{ t: "Automate PTO-vs-crew-minimum check", d: "This conflict has happened 4 times this year. Make it a standing rule.", tag: "SYSTEMIZE" }, { t: "Connect the fleet telematics feed", d: "Adds truck location to the graph — cuts dispatch guesswork.", tag: "COMPOUND" }] },
      ],
    },
    compliance: {
      tiles: [{ label: "OPEN FINDINGS", val: "3", color: "#B47614" }, { label: "HIGH SEVERITY", val: "1", color: "#C7452F" }, { label: "PASSED CHECKS", val: "47", color: "#15854F" }, { label: "NEXT AUDIT", val: "38 days", color: "#14181C" }],
      findings: [
        { sev: "HIGH", rule: "OSHA 300 log — 2 unrecorded March incidents", detail: "IR-031 and IR-034 are recordable under 29 CFR 1904 but absent from the log.", status: "OPEN" },
        { sev: "MED", rule: "NERC PRC-005 — relay test interval", detail: "Substation 2 relay bank is 11 days past its maintenance interval per Maximo history.", status: "OPEN" },
        { sev: "MED", rule: "I-9 documentation — 3 files incomplete", detail: "ADP shows 3 active employees with missing Section 2 verification.", status: "IN REVIEW" },
        { sev: "PASS", rule: "EPA SPCC plan — annual review", detail: "Reviewed and signed 04/2026. Next review due 04/2027.", status: "CURRENT" },
      ],
      audit: [
        { time: "06:14", text: "T-114 thermal exposure logged; recommendation generated and timestamped." },
        { time: "05:41", text: "Crew shortage detected — ADP PTO joined against Maximo WO-2291 minimums." },
        { time: "Mon", text: "OSHA 300 gap identified by cross-referencing SharePoint incident reports." },
        { time: "Mon", text: "PRC-005 interval check ran against Maximo maintenance history — 1 exception." },
        { time: "Sun", text: "Weekly full-graph compliance sweep: 47 checks passed, 3 findings open." },
      ],
    },
    people: [
      {
        initials: "RM", name: "Rosa Mendez", dept: "FIELD OPS", role: "Field Operations Manager", email: "r.mendez@ggs.com", phone: "(404) 555-0142", status: "red",
        issue: "T-114 thermal risk — needs crew 7 diverted for inspection today.", unread: 2,
        thread: [{ from: "nadir", text: "Heads up: T-114 crossed its thermal threshold at 06:12. Crew 7 is closest." }, { from: "them", text: "Saw the alert. Can we cover it without pulling crew 7 off the Feeder 8 job?" }, { from: "them", text: "Also — are we still 2 short for Thursday?" }],
        draft: "Rosa — keep crew 7 on Feeder 8; they pass Sub 4 at 14:30, do the T-114 thermal scan then. Thursday shortage is solved: moving crews 3 & 9 off WO-2307. Plan attached.",
      },
      {
        initials: "DT", name: "Derek Tran", dept: "COMPLIANCE", role: "EHS & Compliance Lead", email: "d.tran@ggs.com", phone: "(404) 555-0187", status: "amber",
        issue: "OSHA 300 log missing IR-031 & IR-034; PRC-005 relay interval overdue.", unread: 1,
        thread: [{ from: "them", text: "Did the weekend sweep flag anything I need before the audit window?" }, { from: "nadir", text: "Two OSHA 300 entries are missing and one relay bank is past interval. Both drafted." }],
        draft: "Derek — pre-filled OSHA 300 entries for IR-031/IR-034 are ready for your signature, and I’ve queued the PRC-005 relay bank into next week’s maintenance. Sign and both findings close.",
      },
      {
        initials: "PW", name: "Priya Walsh", dept: "HR", role: "HR Business Partner", email: "p.walsh@ggs.com", phone: "(404) 555-0119", status: "amber",
        issue: "3 I-9 files incomplete; PTO approvals collided with Thursday crew minimum.", unread: 0,
        thread: [{ from: "nadir", text: "FYI — 3 active employees have incomplete I-9 Section 2 verification in ADP." }],
        draft: "Priya — flagging 3 incomplete I-9s (list attached). Also, the Thursday PTO approvals put Feeder 12 below crew minimum; ops has a fix, no action needed from you, just visibility.",
      },
    ],
    graph: {
      nodes: [
        { label: "ADP", type: "source", x: 10, y: 18, meta: "HR system of record. Feeds the Crew object: rosters, PTO, certifications.", derivation: [{ step: "READ", text: "Schema pulled read-only from ADP Workforce Now." }, { step: "MAP", text: 'emp_roster_v3 proposed as "Crews / People" — confirmed by ops manager.' }, { step: "LINK", text: "Joined to Work Orders via assigned_crew_id." }] },
        { label: "Maximo", type: "source", x: 10, y: 42, meta: "Asset management. Feeds Work Orders and Asset condition history.", derivation: [{ step: "READ", text: "Direct SQL read of Maximo wo_master + asset_registry." }, { step: "MAP", text: "Two tables mapped to Work Orders and Assets." }, { step: "LINK", text: "Asset condition history joined to PI telemetry by tag." }] },
        { label: "PI Historian", type: "source", x: 10, y: 66, meta: "SCADA time-series. Feeds live Asset telemetry — temperatures, loads, states.", derivation: [{ step: "READ", text: "Streaming read of PI tag hierarchy (8.1M hourly points)." }, { step: "MAP", text: "Tags matched to physical Assets by naming + location." }, { step: "WATCH", text: "T-114 temp trend compared against T-109 pre-failure signature." }] },
        { label: "SharePoint", type: "source", x: 10, y: 88, meta: "Unstructured docs. Feeds Incidents and compliance filings via document parsing.", derivation: [{ step: "READ", text: "Document library indexed and parsed." }, { step: "MAP", text: "Incident reports extracted to structured Incidents." }, { step: "LINK", text: "Cross-checked against OSHA 300 log — 2 gaps found." }] },
        { label: "Crews", type: "object", x: 36, y: 22, meta: "14 crews, 340 people. Linked to work orders, certifications, and PTO calendar.", derivation: [{ step: "FROM", text: "Built from ADP roster + certification records." }, { step: "LINK", text: "PTO calendar joined to scheduling constraints." }] },
        { label: "Work Orders", type: "object", x: 36, y: 50, meta: "12,410 records. Each links a crew, an asset, materials, and a compliance requirement.", derivation: [{ step: "FROM", text: "Maximo wo_master, confirmed 98%." }, { step: "LINK", text: "Each WO joins Crew + Asset + Filing." }] },
        { label: "Assets", type: "object", x: 36, y: 76, meta: "2,180 tracked assets. Live telemetry joined to maintenance history.", derivation: [{ step: "FROM", text: "Maximo asset_registry + PI live tags." }, { step: "WATCH", text: "T-114 flagged as a live risk node." }] },
        { label: "Scheduling", type: "process", x: 63, y: 30, meta: "Where crews meet work orders. Current constraint: Thursday PTO conflict.", derivation: [{ step: "INFER", text: "Process inferred from crew↔WO assignment timestamps." }, { step: "FLAG", text: "Thursday minimum-crew constraint violated." }] },
        { label: "Field Work", type: "process", x: 63, y: 62, meta: "Execution flow: dispatch → work → closeout → filing.", derivation: [{ step: "INFER", text: "Flow reconstructed from WO status transitions." }] },
        { label: "T-114 risk", type: "risk", x: 86, y: 46, meta: "Live risk node. Thermal trend matches the T-109 pre-failure signature. Plan attached.", derivation: [{ step: "SIGNAL", text: "PI temp trend +8°C over norm at 06:12." }, { step: "MATCH", text: "Pattern matches T-109 (Aug ’25) pre-failure." }, { step: "ACT", text: "Inspection + load-shift plan generated." }] },
      ],
      edges: [[0, 4], [1, 5], [1, 6], [2, 6], [3, 5], [4, 7], [5, 7], [5, 8], [6, 8], [7, 9], [8, 9], [6, 9]],
    },
    obTables: [{ name: "wo_master", rows: "12,410" }, { name: "emp_roster_v3", rows: "340" }, { name: "asset_registry", rows: "2,180" }, { name: "pi_tags_hourly", rows: "8.1M" }, { name: "incident_docs", rows: "4,120" }],
    obMappings: [{ table: "wo_master", proposed: "Work Orders", conf: "98% confident" }, { table: "emp_roster_v3", proposed: "Crews / People", conf: "96% confident" }, { table: "asset_registry", proposed: "Assets", conf: "99% confident" }, { table: "pi_tags_hourly", proposed: "Asset Telemetry", conf: "93% confident" }, { table: "incident_docs", proposed: "Incidents & Filings", conf: "88% confident" }],
    obDone: "5 tables mapped to real-world objects. 12 relationships inferred from keys and timestamps.",
  },
  {
    id: "manufacturing",
    name: "Hartwell Pencil Co.",
    industry: "Manufacturing · 146 on shift",
    nowMin: 430,
    sources: [
      { name: "SAP Business One", meta: "ERP · 61k rows", node: 0 },
      { name: "Ignition SCADA", meta: "Floor systems · live", node: 1 },
      { name: "ADP", meta: "HR · 212 records", node: 2 },
      { name: "QuickBooks", meta: "Finance · 9,340 txns", node: 3 },
      { name: "inventory_final_v7.xlsx", meta: "Spreadsheet · 1,806 rows", node: 4 },
    ],
    kpis: [{ label: "LINES RUNNING", val: "2 / 3", color: "#C7452F" }, { label: "OEE TODAY", val: "71%", color: "#B47614" }, { label: "SHIP-HOLD RISK", val: "1 lot", color: "#B47614" }, { label: "MEALS VS ROSTER", val: "−26", color: "#C7452F" }],
    alerts: [
      { sev: "CRITICAL", color: "#C7452F", at: 422, time: "07:02", title: "Line 3 kiln down — cedar backlog forming", detail: "Ignition fault E-217. Slat backlog at station 4 hits bottleneck in 3.2 hours at current takt.", loc: "Floor · Line 3", q: "Walk me through the kiln fix" },
      { sev: "WARNING", color: "#B47614", at: 0, time: "Tmrw", title: "120 meals ordered, 146 on shift roster", detail: "Catering PO in QuickBooks doesn’t match the ADP roster after Saturday overtime approvals. 26 short.", loc: "Facilities", q: "Fix tomorrow’s meal order" },
      { sev: "WARNING", color: "#B47614", at: 0, time: "6/28", title: "Graphite lot #88 — supplier cert expired", detail: "Cert lapsed 6/28 in SAP. Lot feeds Friday’s export order. Ship-hold risk if unresolved.", loc: "QA · receiving", q: "What about lot #88?" },
    ],
    intro: "Morning read: 5 systems reconciled, including the spreadsheet nobody admits is load-bearing.\n\n1. Line 3's kiln has been down 41 minutes — backlog hits the bottleneck in ~3 hours.\n2. Tomorrow you ordered 120 meals for a 146-person roster. The catering PO never saw Saturday's overtime approvals.\n3. Graphite lot #88's supplier cert expired — it feeds Friday's export order.\n\nWhich first?",
    suggestions: ["Walk me through the kiln fix", "Fix tomorrow’s meal order", "What about lot #88?"],
    replies: [
      { text: "Kiln E-217 has occurred twice before — March 2024 and Nov 2025. Both times it was the feed damper actuator, not the burner. Repair took 90 minutes once the right part was in hand.\n\n1. Part #KD-3341 is in stores (bin 14-C, qty 2, per SAP).\n2. Reroute slats to Line 1's kiln at half-rate — buys 2 hours of buffer.\n3. If it's not the actuator, the fault history says call Vesta Services; they've closed every other E-217 same-day.\n\nMaintenance ticket drafted. File it?", cites: ["Ignition · fault log E-217", "SAP · stores bin 14-C", "Maintenance history · Mar ’24, Nov ’25"] },
      { text: "The meal gap is a join nobody does: ADP approved 26 overtime shifts on Saturday, the catering PO in QuickBooks was cut on Friday.\n\nI've drafted an amended PO for 150 meals (146 + buffer) to the same vendor — cutoff for tomorrow delivery is 16:00 today. Approve and it goes out.\n\nAlso: this is the third roster-vs-order mismatch this quarter. I can make it a standing check so it never reaches you again.", cites: ["ADP · OT approvals 6/28", "QuickBooks · PO-8841"] },
      { text: "Lot #88 options, in order of cost:\n\nA. The supplier's updated cert may already exist — their portal shows a renewal issued 6/30. I've requested the document; if it lands, this closes for free.\nB. Swap in lot #85 (certified, 340kg on hand) for Friday's export run and burn #88 domestically after recert.\n\nEither way Friday ships. A costs nothing; B costs a re-stage. Start with A, fall back to B Thursday noon.", cites: ["SAP · lot #88, #85", "Supplier portal · cert renewal 6/30"] },
    ],
    action: { title: "Snapshot ready for plant manager", desc: "Kiln status, meal fix, and lot #88 plan on one page — drafted for the 09:30 floor meeting." },
    plan: {
      subtitle: "Today’s sequence for the floor — ordered by cost of waiting.",
      why: "The kiln is first because the backlog compounds by the hour; the meal PO has a hard 16:00 vendor cutoff; lot #88 has until Thursday noon before the fallback swap must start.",
      cols: [
        { title: "NOW · TODAY", color: "#C7452F", items: [{ t: "Swap kiln feed damper actuator", d: "Part in bin 14-C. Same fault, same fix, twice before — 90 min.", tag: "STOPS BLEEDING" }, { t: "Amend catering PO to 150 by 16:00", d: "Vendor cutoff is hard. Draft is ready for approval.", tag: "HARD DEADLINE" }] },
        { title: "NEXT · THIS WEEK", color: "#B47614", items: [{ t: "Chase lot #88 cert / stage lot #85", d: "Renewal likely exists. Decision point Thursday noon.", tag: "SHIP FRIDAY" }, { t: "Post-mortem the E-217 pattern", d: "Three occurrences. Price a spare actuator on the shelf vs downtime.", tag: "PREVENT REPEAT" }] },
        { title: "LATER · THIS QUARTER", color: "#15854F", items: [{ t: "Standing roster-vs-orders check", d: "Meals today; materials and staffing tomorrow. Same join, automated.", tag: "SYSTEMIZE" }, { t: "Retire inventory_final_v7.xlsx", d: "It’s load-bearing and unversioned. Migrate to SAP or keep it synced.", tag: "DE-RISK" }] },
      ],
    },
    compliance: {
      tiles: [{ label: "OPEN FINDINGS", val: "2", color: "#B47614" }, { label: "HIGH SEVERITY", val: "1", color: "#C7452F" }, { label: "PASSED CHECKS", val: "31", color: "#15854F" }, { label: "EXPORT DOCS", val: "AT RISK", color: "#B47614" }],
      findings: [
        { sev: "HIGH", rule: "Supplier certification — graphite lot #88", detail: "Cert lapsed 6/28. Lot is allocated to Friday’s export order; shipping uncertified material is a violation.", status: "OPEN" },
        { sev: "MED", rule: "OSHA machine guarding — Line 2 station 6", detail: "Guard interlock bypassed 4 times this month per Ignition event log.", status: "OPEN" },
        { sev: "PASS", rule: "Hazcom — SDS binder current", detail: "All 34 chemicals on floor have current sheets on file.", status: "CURRENT" },
        { sev: "PASS", rule: "Forklift certifications", detail: "12 of 12 operators current in ADP training records.", status: "CURRENT" },
      ],
      audit: [
        { time: "07:02", text: "Line 3 downtime logged with fault code, backlog projection, and response plan." },
        { time: "06:55", text: "Meal/roster mismatch flagged — QuickBooks PO joined against ADP shift roster." },
        { time: "6/28", text: "Lot #88 cert expiry detected on SAP receiving record; export allocation cross-checked." },
        { time: "6/27", text: "Guard interlock bypass pattern surfaced from Ignition event log — 4 events." },
        { time: "6/25", text: "Weekly sweep: 31 checks passed, 2 findings open." },
      ],
    },
    people: [
      {
        initials: "MK", name: "Marcus Kim", dept: "FLOOR", role: "Line 3 Supervisor", email: "m.kim@hartwell.co", phone: "(912) 555-0164", status: "red",
        issue: "Kiln E-217 down 41 min; cedar backlog building at station 4.", unread: 3,
        thread: [{ from: "them", text: "Kiln’s down again. Same code as last time?" }, { from: "nadir", text: "Yes — E-217. Both prior times it was the feed damper actuator, not the burner." }, { from: "them", text: "Part in stores?" }, { from: "them", text: "And what do I do with the slat backlog meanwhile?" }],
        draft: "Marcus — actuator #KD-3341 is in bin 14-C, qty 2. Swap it (90 min job, done twice before). Meanwhile reroute slats to Line 1 kiln at half-rate to hold the buffer. Ticket drafted, waiting your OK.",
      },
      {
        initials: "LR", name: "Lena Ruiz", dept: "QA", role: "Quality & Compliance Manager", email: "l.ruiz@hartwell.co", phone: "(912) 555-0198", status: "amber",
        issue: "Graphite lot #88 supplier cert expired; feeds Friday export order.", unread: 1,
        thread: [{ from: "nadir", text: "Lot #88 cert lapsed 6/28 and it’s allocated to Friday’s export run." }, { from: "them", text: "Do we have a certified substitute or do we hold the shipment?" }],
        draft: "Lena — supplier portal shows a renewed cert issued 6/30; I’ve requested the doc. If it lands by Thursday noon, #88 is clean. If not, swap in lot #85 (certified, 340kg on hand). Either way Friday ships.",
      },
      {
        initials: "BC", name: "Bev Carter", dept: "FACILITIES", role: "Facilities & Catering", email: "b.carter@hartwell.co", phone: "(912) 555-0121", status: "amber",
        issue: "Tomorrow: 120 meals ordered vs 146 on roster after OT approvals.", unread: 0,
        thread: [{ from: "nadir", text: "Tomorrow’s catering PO is 26 short — Saturday OT approvals landed after the PO was cut." }],
        draft: "Bev — amended PO for 150 meals is drafted to the same vendor. Their cutoff for tomorrow is 16:00 today. Approve it and we’re covered; I’ll also set a standing roster-vs-order check so this stops recurring.",
      },
    ],
    graph: {
      nodes: [
        { label: "SAP B1", type: "source", x: 10, y: 18, meta: "ERP. Feeds Inventory, Orders, and supplier records.", derivation: [{ step: "READ", text: "Direct SQL read of SAP Business One." }, { step: "MAP", text: "OITM_items → Inventory (99%)." }, { step: "LINK", text: "Supplier cert dates joined to lot records." }] },
        { label: "Ignition", type: "source", x: 10, y: 42, meta: "Floor SCADA. Feeds Machines: states, faults, counts.", derivation: [{ step: "READ", text: "Streaming read of Ignition event tags." }, { step: "WATCH", text: "Fault E-217 matched to Line 3 kiln." }] },
        { label: "ADP", type: "source", x: 10, y: 66, meta: "HR. Feeds Shifts: roster, overtime, certifications.", derivation: [{ step: "READ", text: "ADP shift + roster tables read." }, { step: "LINK", text: "OT approvals joined to catering PO." }] },
        { label: "QuickBooks", type: "source", x: 10, y: 88, meta: "Finance. Feeds POs and invoices — including catering.", derivation: [{ step: "READ", text: "QuickBooks PO + invoice ledger read." }, { step: "FLAG", text: "Catering PO undercount surfaced." }] },
        { label: "Inventory", type: "object", x: 36, y: 22, meta: "1,806 SKUs. Includes the spreadsheet, reconciled nightly against SAP.", derivation: [{ step: "FROM", text: "SAP OITM_items + shadow spreadsheet." }, { step: "RECONCILE", text: "xlsx reconciled nightly to catch drift." }] },
        { label: "Machines", type: "object", x: 36, y: 50, meta: "3 lines, 14 stations. Live state from Ignition joined to maintenance history.", derivation: [{ step: "FROM", text: "Ignition tags mapped to stations." }, { step: "WATCH", text: "Line 3 kiln flagged as risk." }] },
        { label: "Shifts", type: "object", x: 36, y: 76, meta: "146 on shift tomorrow. Roster, overtime, and meal orders linked here.", derivation: [{ step: "FROM", text: "ADP roster + OT approvals." }, { step: "LINK", text: "Meal PO joined — mismatch found." }] },
        { label: "Production", type: "process", x: 63, y: 34, meta: "Cedar in → slats → pencils → packed. Current takt limited by Line 3.", derivation: [{ step: "INFER", text: "Flow from station throughput counts." }, { step: "FLAG", text: "Line 3 kiln is the current bottleneck." }] },
        { label: "Fulfillment", type: "process", x: 63, y: 66, meta: "Orders → allocation → QA → ship. Friday export order runs through here.", derivation: [{ step: "INFER", text: "Reconstructed from order status flow." }, { step: "FLAG", text: "Lot #88 cert blocks Friday allocation." }] },
        { label: "Line 3 kiln", type: "risk", x: 86, y: 34, meta: "Down 41 min, fault E-217. Fix plan attached — actuator in stores.", derivation: [{ step: "SIGNAL", text: "Ignition fault E-217 at 07:02." }, { step: "MATCH", text: "Same fault Mar ’24 and Nov ’25." }, { step: "ACT", text: "Actuator-swap plan generated." }] },
        { label: "Lot #88 hold", type: "risk", x: 86, y: 66, meta: "Cert lapsed; feeds Friday export. Two-path resolution attached.", derivation: [{ step: "SIGNAL", text: "SAP cert expiry on lot #88." }, { step: "TRACE", text: "Allocated to Friday export order." }, { step: "ACT", text: "Chase-cert / swap-#85 plan generated." }] },
      ],
      edges: [[0, 4], [1, 5], [2, 6], [3, 6], [3, 4], [4, 7], [5, 7], [6, 7], [4, 8], [7, 9], [8, 10], [5, 9]],
    },
    obTables: [{ name: "OITM_items", rows: "1,806" }, { name: "ign_events", rows: "2.4M" }, { name: "adp_shifts", rows: "18,220" }, { name: "qb_purchase_orders", rows: "9,340" }, { name: "inventory_final_v7.xlsx", rows: "1,806" }],
    obMappings: [{ table: "OITM_items", proposed: "Inventory", conf: "99% confident" }, { table: "ign_events", proposed: "Machine Events", conf: "97% confident" }, { table: "adp_shifts", proposed: "Shifts / People", conf: "96% confident" }, { table: "qb_purchase_orders", proposed: "Purchase Orders", conf: "95% confident" }, { table: "inventory_final_v7.xlsx", proposed: "Inventory (shadow copy)", conf: "84% confident" }],
    obDone: "5 tables mapped, including one shadow spreadsheet Nadir now reconciles nightly.",
  },
  {
    id: "staffing",
    name: "Meridian Staffing",
    industry: "Staffing startup · 2 founders, 7 placed",
    nowMin: 600,
    sources: [
      { name: "Google Sheets", meta: "Pipeline · 214 rows", node: 0 },
      { name: "HubSpot", meta: "CRM · 38 contacts", node: 1 },
      { name: "Gusto", meta: "Payroll · 9 records", node: 2 },
      { name: "Notion", meta: "Docs · 86 pages", node: 3 },
    ],
    kpis: [{ label: "RUNWAY", val: "4.2 mo", color: "#B47614" }, { label: "PIPELINE", val: "$86k", color: "#14181C" }, { label: "PLACED", val: "7", color: "#15854F" }, { label: "OVERDUE INVOICES", val: "1", color: "#C7452F" }],
    alerts: [
      { sev: "CRITICAL", color: "#C7452F", at: 0, time: "Now", title: "No signed MSA template — blocking 2 pending clients", detail: "Both deals in HubSpot are stalled at “contract” stage. There is no master services agreement anywhere in Notion or Drive.", loc: "Legal · contracts", q: "How do I get an MSA?" },
      { sev: "WARNING", color: "#B47614", at: 0, time: "Now", title: "Runway 4.2 months at current burn", detail: "Gusto payroll plus recurring spend against the bank feed. One more placement extends it to 5.8.", loc: "Finance", q: "How do I extend runway?" },
      { sev: "WARNING", color: "#B47614", at: 0, time: "12 d", title: "Invoice #0007 overdue — $9,400", detail: "Sent 12 days ago, no payment, no follow-up email on record in HubSpot.", loc: "AR", q: "Draft the invoice follow-up" },
    ],
    intro: "I've read your pipeline sheet, HubSpot, Gusto, and Notion. You're earlier-stage than the last two companies in this demo, so the guidance is more zero-to-one.\n\n1. Two clients are stuck at contract stage because you don't have an MSA. This is your bottleneck — not sales.\n2. Invoice #0007 ($9,400) is 12 days overdue and nobody has followed up.\n3. Runway is 4.2 months. One placement extends it to 5.8.\n\nThe MSA is the highest-leverage fix. Want the plan?",
    suggestions: ["How do I get an MSA?", "Draft the invoice follow-up", "How do I find my next client?"],
    replies: [
      { text: "MSA, fastest credible path:\n\n1. Start from a staffing-specific template (SHRM and Priori both publish them) — do not write one from scratch.\n2. Get a flat-fee review from an employment attorney — typical range $500–$1,500, 3–5 days. You need staffing-specific indemnification and co-employment language; this is not optional in your industry.\n3. Send to both stalled clients the day it's back.\n\nBoth deals total $31k. A $1,000 legal spend to unblock $31k is the easiest decision in your pipeline. I can draft the attorney outreach email now.", cites: ["HubSpot · 2 deals at contract stage", "Pipeline sheet · deal values"] },
      { text: 'Follow-up drafted:\n\n"Hi Dana — flagging invoice #0007 ($9,400, due 6/20) as past due. Happy to resend or set up ACH if easier. Could you confirm payment timing this week?"\n\nFirm, warm, no apology. If no reply in 3 business days, the next one goes to their AP address with the original attached. After that, a call — 90% of first-invoice delays at this size are process, not solvency.\n\nAlso: your invoices don’t state payment terms. Add "Net 15" to the template and this stops recurring.', cites: ["HubSpot · no follow-up logged", "Invoice #0007 · sent 6/20"] },
      { text: "Your own data answers this: all 7 placements came from 2 clients, both in healthcare admin, both found via referral — zero from cold outreach (38 contacts, 0 conversions).\n\nSo: don't scale cold email. Work the referral vein.\n\n1. Ask both active clients for one introduction each — you have a 100% close rate on referrals.\n2. Join the two regional healthcare HR associations your clients belong to (they're listed on their sites).\n3. The MSA has to come first — a referral you can't sign is a referral you lose.", cites: ["Pipeline sheet · source column", "HubSpot · conversion by channel"] },
    ],
    action: { title: "Founder briefing ready", desc: "One page: the MSA bottleneck, the $31k it unblocks, and this week’s three moves. Send to your co-founder." },
    plan: {
      subtitle: "Zero to one hundred — the order matters more than the effort.",
      why: "The MSA is sequenced first because it unblocks $31k already in pipeline; cash actions come before growth actions because runway is the clock everything else runs on.",
      cols: [
        { title: "NOW · THIS WEEK", color: "#C7452F", items: [{ t: "Get the MSA reviewed and signed", d: "Template + flat-fee attorney review. Unblocks $31k in stalled deals.", tag: "UNBLOCKS REVENUE" }, { t: "Chase invoice #0007", d: "Follow-up drafted. $9,400 is 7% of your runway.", tag: "CASH" }, { t: "Add Net 15 terms to invoice template", d: "Prevents the next overdue before it happens.", tag: "5-MIN FIX" }] },
        { title: "NEXT · THIS MONTH", color: "#B47614", items: [{ t: "Ask both clients for one referral each", d: "100% historical close rate on referrals vs 0% on cold.", tag: "GROWTH" }, { t: "Workers’ comp + liability COI", d: "Every serious client will require it. Get quotes before they ask.", tag: "REMOVES FRICTION" }] },
        { title: "LATER · THIS QUARTER", color: "#15854F", items: [{ t: "Move pipeline off Google Sheets", d: "When you pass ~30 active candidates, the sheet becomes the bottleneck.", tag: "SCALE PREP" }, { t: "Seed conversations — only after 3 clients", d: "A working referral engine is a fundable story. An idea is not.", tag: "FUNDING PATH" }] },
      ],
    },
    compliance: {
      tiles: [{ label: "OPEN FINDINGS", val: "3", color: "#B47614" }, { label: "HIGH SEVERITY", val: "1", color: "#C7452F" }, { label: "PASSED CHECKS", val: "12", color: "#15854F" }, { label: "ENTITY STATUS", val: "GOOD", color: "#15854F" }],
      findings: [
        { sev: "HIGH", rule: "No MSA / contractor agreements on file", detail: "Placements are operating on email threads. Co-employment liability is unbounded without signed agreements.", status: "OPEN" },
        { sev: "MED", rule: "W-9s missing for 2 contractors", detail: "Gusto shows 2 of 9 contractor files without W-9s. Needed before any 1099 filing.", status: "OPEN" },
        { sev: "MED", rule: "Workers’ comp coverage not found", detail: "No policy detected in expenses or docs. Most client contracts will require a COI.", status: "OPEN" },
        { sev: "PASS", rule: "State registration & EIN", detail: "Entity in good standing; payroll registrations current in Gusto.", status: "CURRENT" },
      ],
      audit: [
        { time: "Today", text: "Contract-stage stall linked to missing MSA — flagged as revenue-blocking." },
        { time: "Today", text: "Runway recomputed from Gusto payroll + bank feed: 4.2 months." },
        { time: "6/30", text: "Invoice #0007 aged past 10 days with no follow-up on record." },
        { time: "6/28", text: "W-9 gap detected across contractor files in Gusto." },
        { time: "6/25", text: "Initial compliance baseline: 12 checks passed, 3 findings open." },
      ],
    },
    people: [
      {
        initials: "JD", name: "Jordan Diaz", dept: "CO-FOUNDER", role: "Co-founder / Sales", email: "jordan@meridianstaff.co", phone: "(678) 555-0155", status: "red",
        issue: "Two deals stalled at contract stage — no MSA to sign.", unread: 2,
        thread: [{ from: "them", text: "Both my healthcare deals went quiet. Did I lose them?" }, { from: "nadir", text: "No — they’re stuck at “contract” in HubSpot. You have no MSA to send them." }, { from: "them", text: "So it’s not a sales problem?" }],
        draft: "Jordan — it’s not sales, it’s paperwork. Both deals ($31k total) are waiting on an MSA. A $1k flat-fee attorney review unblocks them this week. Attorney outreach email drafted — want me to send?",
      },
      {
        initials: "AT", name: "Amara Twinam", dept: "FINANCE", role: "Co-founder / Ops & Finance", email: "amara@meridianstaff.co", phone: "(678) 555-0173", status: "amber",
        issue: "Runway 4.2 mo; invoice #0007 ($9,400) 12 days overdue.", unread: 1,
        thread: [{ from: "nadir", text: "Invoice #0007 is 12 days overdue with no follow-up logged. That’s 7% of runway sitting idle." }, { from: "them", text: "Ugh. Can you draft something that isn’t awkward?" }],
        draft: "Amara — follow-up for #0007 is drafted (firm, warm, no apology). If no reply in 3 business days it escalates to their AP contact. Also adding “Net 15” to the invoice template so this stops happening.",
      },
    ],
    graph: {
      nodes: [
        { label: "Sheets", type: "source", x: 10, y: 20, meta: "Pipeline spreadsheet. Feeds Candidates and deal sources.", derivation: [{ step: "READ", text: "Google Sheet pipeline parsed." }, { step: "MAP", text: "Rows → Candidates (91%)." }, { step: "ANALYZE", text: "Source column shows 100% of placements from referrals." }] },
        { label: "HubSpot", type: "source", x: 10, y: 44, meta: "CRM. Feeds Clients, deals, and outreach history.", derivation: [{ step: "READ", text: "HubSpot contacts + deal stages read." }, { step: "FLAG", text: "2 deals stuck at contract stage." }] },
        { label: "Gusto", type: "source", x: 10, y: 68, meta: "Payroll. Feeds Contractors and burn rate.", derivation: [{ step: "READ", text: "Gusto payroll records read." }, { step: "COMPUTE", text: "Burn rate → 4.2 months runway." }] },
        { label: "Notion", type: "source", x: 10, y: 88, meta: "Docs. Searched for contracts, SOPs, and templates — MSA not found.", derivation: [{ step: "READ", text: "86 Notion pages indexed." }, { step: "SEARCH", text: "No MSA or contractor agreement found anywhere." }] },
        { label: "Candidates", type: "object", x: 36, y: 26, meta: "214 tracked. 7 placed, all via referral-sourced clients.", derivation: [{ step: "FROM", text: "Pipeline sheet rows." }, { step: "LINK", text: "Joined to Clients by placement." }] },
        { label: "Clients", type: "object", x: 36, y: 54, meta: "2 active + 2 stalled at contract stage. Both stalls share one cause.", derivation: [{ step: "FROM", text: "HubSpot deals + contacts." }, { step: "FLAG", text: "Both stalls trace to the MSA gap." }] },
        { label: "Cash", type: "object", x: 36, y: 80, meta: "Burn from Gusto + bank feed. Runway 4.2 months.", derivation: [{ step: "FROM", text: "Gusto + bank feed." }, { step: "WATCH", text: "Overdue invoice = 7% of runway." }] },
        { label: "Placements", type: "process", x: 63, y: 38, meta: "Source → screen → place → invoice. Conversion is 100% referral-driven.", derivation: [{ step: "INFER", text: "Flow from candidate status history." }] },
        { label: "Billing", type: "process", x: 63, y: 70, meta: "Invoice → payment → payroll. One invoice aging, no terms on template.", derivation: [{ step: "INFER", text: "Reconstructed from invoice + payment records." }, { step: "FLAG", text: "#0007 overdue, no terms set." }] },
        { label: "MSA gap", type: "risk", x: 86, y: 52, meta: "Root blocker. Stalls $31k in deals and leaves co-employment risk unbounded.", derivation: [{ step: "SIGNAL", text: "2 deals stuck at contract stage." }, { step: "SEARCH", text: "No MSA found in Notion or Drive." }, { step: "ACT", text: "Template + attorney-review plan generated." }] },
      ],
      edges: [[0, 4], [1, 5], [2, 6], [3, 9], [4, 7], [5, 7], [5, 9], [6, 8], [7, 8], [9, 5], [8, 6]],
    },
    obTables: [{ name: "Pipeline (Sheet1)", rows: "214" }, { name: "hubspot_contacts", rows: "38" }, { name: "gusto_people", rows: "9" }, { name: "notion_pages", rows: "86" }],
    obMappings: [{ table: "Pipeline (Sheet1)", proposed: "Candidates", conf: "91% confident" }, { table: "hubspot_contacts", proposed: "Clients / Contacts", conf: "95% confident" }, { table: "gusto_people", proposed: "Contractors", conf: "97% confident" }, { table: "notion_pages", proposed: "Documents & SOPs", conf: "89% confident" }],
    obDone: "4 sources mapped. Nadir found the MSA gap during this scan — before you asked.",
  },
];
