export const ROLES = [
  {
    slug: "founding-fusion-engineer",
    title: "Founding Fusion Engineer",
    team: "Engineering",
    location: "Atlanta · Hybrid",
    type: "Full-time",
    shortDesc: "Own the data ingestion layer. Connect to legacy ERPs and build the operational graph.",
    about: "We need someone to own the entire data ingestion pipeline. You'll write the code that connects to messy, on-premise ERP systems (Oracle, SAP, custom databases) and turns ten disjointed data sources into one clean, unified operational graph. This is not a data engineering job at a company that moves CSVs around — you'll be parsing schemas that were designed in the late 90s and building fault-tolerant systems that handle real-time operational data for regulated industries.",
    whatYoullDo: [
      "Build and maintain robust connectors for legacy database systems (Oracle, MSSQL, SAP HANA, custom ERPs)",
      "Design heuristics that automatically infer schema structures from poorly documented databases",
      "Implement the identity resolution layer that matches entities across disconnected systems",
      "Work directly with customers to understand their data landscape during the first two weeks of deployment",
      "Contribute to the core ontology mapping engine that translates raw columns into semantic objects",
    ],
    whatWereLookingFor: [
      "Deep experience with relational databases and SQL (not just SELECT *)",
      "Comfort working with legacy systems, messy data, and incomplete documentation",
      "Strong fundamentals in data engineering, ETL pipelines, or database internals",
      "Ability to work directly with non-technical stakeholders (plant managers, compliance officers)",
      "Experience with Python, TypeScript, or Go",
    ],
  },
  {
    slug: "forward-deployed-engineer",
    title: "Forward-Deployed Engineer",
    team: "Deployment",
    location: "Remote (US) / Travel required",
    type: "Full-time",
    shortDesc: "Travel to client sites. Hook up their databases. Find hidden risks in two weeks.",
    about: "You'll be the bridge between our product and our enterprise clients. You'll travel to client sites, orchestrate the connection of their databases to the Nadir platform, and guide them through confirming their operational ontology. Your mandate: help the client uncover hidden operational risks or compliance violations within the first two weeks of deployment.",
    whatYoullDo: [
      "Lead on-site deployments at customer facilities (manufacturing plants, utility companies, aerospace firms)",
      "Connect customer databases to the Nadir ingestion pipeline and validate data quality",
      "Guide customers through the ontology confirmation process using the visual schema mapper",
      "Identify and surface the first high-value compliance insights within the initial deployment window",
      "Feed customer-specific requirements back to the core engineering team to improve the product",
    ],
    whatWereLookingFor: [
      "Willingness to travel to customer sites (typically 30–50% travel)",
      "Strong SQL skills and comfort navigating unfamiliar database environments",
      "Excellent communication skills — you'll be working with plant managers and C-suite executives",
      "Self-directed and comfortable operating with high autonomy",
      "Prior experience in consulting, solutions engineering, or customer-facing technical roles",
    ],
  },
  {
    slug: "product-design-engineer",
    title: "Product Design Engineer",
    team: "Product",
    location: "Remote (US)",
    type: "Full-time",
    shortDesc: "Design the interface our customers rely on daily. Make dense data obvious.",
    about: "You'll design and build the interface that operations managers, compliance officers, and CEOs rely on every day. The core challenge is taking incredibly dense, multi-dimensional operational data — alerts, KPIs, compliance violations, shift schedules, machine status — and making it instantly understandable to someone who has never used software like this before.",
    whatYoullDo: [
      "Design and implement the workspace UI using React, Next.js, and CSS",
      "Build interactive data visualizations for the operational graph and compliance dashboard",
      "Create responsive layouts that work for factory line workers on mobile and executives on desktop",
      "Prototype and iterate on new features based on direct customer feedback",
      "Maintain the design system and ensure visual consistency across the entire platform",
    ],
    whatWereLookingFor: [
      "Strong React and CSS skills (not just Tailwind — you need to understand layout fundamentals)",
      "Experience designing for data-heavy applications (dashboards, analytics, operational tools)",
      "Ability to balance information density with clarity",
      "Comfort working in a small team where you own the entire design-to-implementation pipeline",
      "Portfolio or examples of complex UI work",
    ],
  },
];
