import type { Metadata } from "next";
import { PageHero, Section, ContentBlock } from "@/components/site/PageShell";

export const metadata: Metadata = { title: "Terms of Service — Nadir" };

export default function TermsPage() {
  return (
    <>
      <PageHero
        eyebrow="LEGAL"
        title="Terms of Service"
        sub="Last Updated: July 3, 2026. These terms govern your access to and use of the Nadir platform and related services."
      />
      <Section>
        <ContentBlock n="01" title="1. Agreement and Definitions">
          <p style={{ marginBottom: 16 }}>
            This Master Subscription Agreement ("Agreement") is entered into by and between Nadir Intelligence, Inc. ("Nadir", "Company", "we", or "us") and the entity or person placing an order for or accessing the Services ("Customer", "you").
          </p>
          <p>
            "Services" refers to the Nadir enterprise software platform, including the Ontology Engine, the Operational Graph, and all associated APIs, integrations, and documentation provided by Nadir. "Customer Data" refers to all electronic data, information, or material submitted to the Services by the Customer.
          </p>
        </ContentBlock>

        <ContentBlock n="02" title="2. Provision of Services and Access Rights">
          <p style={{ marginBottom: 16 }}>
            <strong>2.1 License Grant.</strong> Subject to the terms and conditions of this Agreement, Nadir grants Customer a non-exclusive, non-transferable, non-sublicensable right to access and use the Services during the applicable Subscription Term, solely for Customer's internal business operations.
          </p>
          <p style={{ marginBottom: 16 }}>
            <strong>2.2 Customer Responsibilities.</strong> Customer is responsible for all activities conducted under its User accounts. Customer shall ensure that its use of the Services complies with all applicable laws and regulations, including but not limited to privacy, data protection, and export control laws.
          </p>
          <p>
            <strong>2.3 Usage Restrictions.</strong> Customer shall not: (a) reverse engineer, decompile, or disassemble the Services; (b) attempt to derive the source code, underlying ideas, algorithms, structure, or organizational form of the Services; (c) use the Services to build a competitive product or service; or (d) input any Customer Data that is infringing, libelous, defamatory, or otherwise unlawful.
          </p>
        </ContentBlock>

        <ContentBlock n="03" title="3. Data Ownership and Confidentiality">
          <p style={{ marginBottom: 16 }}>
            <strong>3.1 Customer Data.</strong> As between the parties, Customer retains all right, title, and interest in and to all Customer Data. Customer grants Nadir a limited, non-exclusive license to use, process, and transmit Customer Data solely as necessary to provide the Services and perform its obligations under this Agreement.
          </p>
          <p style={{ marginBottom: 16 }}>
            <strong>3.2 Resultant Data.</strong> The unique Ontologies, Schema Maps, and Operational Graphs generated by Nadir specific to the Customer's environment are considered Customer Data and remain the sole property of the Customer upon termination of this Agreement.
          </p>
          <p>
            <strong>3.3 Confidentiality.</strong> Both parties agree to protect each other's Confidential Information using the same degree of care they use to protect their own similar information, but no less than a reasonable degree of care. Nadir specifically agrees that all Customer Data, database schemas, and operational workflows constitute the Customer's highly Confidential Information.
          </p>
        </ContentBlock>

        <ContentBlock n="04" title="4. Disclaimer of Warranties">
          <p>
            THE SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE." NADIR DOES NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED, ERROR-FREE, OR COMPLETELY SECURE. WHILE NADIR PROVIDES DETERMINISTIC OPERATIONAL INTELLIGENCE, THE SERVICES DO NOT GUARANTEE REGULATORY COMPLIANCE, THE PREVENTION OF PHYSICAL INCIDENTS, OR THE AVOIDANCE OF BUSINESS DISRUPTIONS. THE CUSTOMER REMAINS SOLELY RESPONSIBLE FOR ITS OWN OPERATIONAL SAFETY AND LEGAL COMPLIANCE.
          </p>
        </ContentBlock>

        <ContentBlock n="05" title="5. Limitation of Liability">
          <p style={{ marginBottom: 16 }}>
            <strong>5.1 Exclusion of Indirect Damages.</strong> IN NO EVENT WILL EITHER PARTY BE LIABLE TO THE OTHER FOR ANY INDIRECT, SPECIAL, INCIDENTAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES (INCLUDING LOSS OF USE, DATA, BUSINESS, OR PROFITS) ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT, REGARDLESS OF THE LEGAL THEORY.
          </p>
          <p>
            <strong>5.2 Liability Cap.</strong> EXCEPT FOR BREACHES OF CONFIDENTIALITY OR INDEMNIFICATION OBLIGATIONS, EACH PARTY'S TOTAL AGGREGATE LIABILITY ARISING OUT OF OR RELATED TO THIS AGREEMENT SHALL NOT EXCEED THE TOTAL AMOUNTS PAID BY CUSTOMER TO NADIR IN THE TWELVE (12) MONTHS PRECEDING THE INCIDENT GIVING RISE TO THE LIABILITY.
          </p>
        </ContentBlock>
      </Section>
    </>
  );
}
