import type { Metadata } from "next";
import Link from "next/link";
import { PageHero, Section } from "@/components/site/PageShell";
import { FileText, Shield, Database, Scale, AlertTriangle } from "lucide-react";

export const metadata: Metadata = { title: "Terms of Service — Nadir" };

const MONO = "var(--font-ibm-plex-mono), monospace";
const SERIF = "var(--font-newsreader), serif";

const TOC = [
  { id: "agreement", label: "Agreement & Definitions", icon: <FileText size={16} /> },
  { id: "access", label: "Access Rights", icon: <Shield size={16} /> },
  { id: "data", label: "Data Ownership", icon: <Database size={16} /> },
  { id: "warranties", label: "Warranties", icon: <AlertTriangle size={16} /> },
  { id: "liability", label: "Liability", icon: <Scale size={16} /> },
];

export default function TermsPage() {
  return (
    <>
      <PageHero
        eyebrow="LEGAL"
        title="Terms of Service"
        sub="Last Updated: July 3, 2026. These terms govern your access to and use of the Nadir platform."
      />

      {/* QUICK NAV */}
      <div style={{ maxWidth: 1040, margin: "0 auto", padding: "0 48px 60px" }}>
        <div style={{ display: "flex", gap: 12, flexWrap: "wrap" }}>
          {TOC.map((item) => (
            <a key={item.id} href={`#${item.id}`} style={{
              display: "inline-flex", alignItems: "center", gap: 8,
              padding: "8px 16px", borderRadius: 8,
              border: "1px solid rgba(20,24,28,0.12)", background: "#FFFFFF",
              fontSize: 13, color: "#3d4750", textDecoration: "none",
              transition: "border-color 0.2s",
            }}>
              {item.icon} {item.label}
            </a>
          ))}
        </div>
      </div>

      {/* CONTENT */}
      <div style={{ maxWidth: 1040, margin: "0 auto", padding: "0 48px" }}>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 280px", gap: 64 }}>
          <div>
            {/* Section 1 */}
            <div id="agreement" style={{ paddingBottom: 48, marginBottom: 48, borderBottom: "1px solid rgba(20,24,28,0.1)" }}>
              <div style={{ fontFamily: MONO, fontSize: 12, color: "#7a848e", letterSpacing: "0.06em", marginBottom: 12 }}>SECTION 01</div>
              <h2 style={{ fontFamily: SERIF, fontWeight: 400, fontSize: 28, margin: "0 0 16px", letterSpacing: "-0.01em", color: "#14181C" }}>Agreement and Definitions</h2>
              <p style={{ fontSize: 15, lineHeight: 1.75, color: "#4a545e", marginBottom: 16 }}>
                This Master Subscription Agreement ("Agreement") is entered into by Nadir Intelligence, Inc. ("Nadir") and the entity or person accessing the Services ("Customer").
              </p>
              <div style={{ background: "#F6F5F3", borderRadius: 8, padding: "16px 20px", fontSize: 14, lineHeight: 1.7, color: "#4a545e" }}>
                <strong style={{ color: "#14181C" }}>Key definitions:</strong><br/>
                • "Services" — The Nadir platform, including the Ontology Engine, Operational Graph, and all APIs.<br/>
                • "Customer Data" — All electronic data submitted to the Services by Customer.<br/>
                • "Resultant Data" — Ontologies, schema maps, and graphs generated by Nadir specific to Customer.
              </div>
            </div>

            {/* Section 2 */}
            <div id="access" style={{ paddingBottom: 48, marginBottom: 48, borderBottom: "1px solid rgba(20,24,28,0.1)" }}>
              <div style={{ fontFamily: MONO, fontSize: 12, color: "#7a848e", letterSpacing: "0.06em", marginBottom: 12 }}>SECTION 02</div>
              <h2 style={{ fontFamily: SERIF, fontWeight: 400, fontSize: 28, margin: "0 0 16px", letterSpacing: "-0.01em", color: "#14181C" }}>Provision of Services and Access Rights</h2>
              <p style={{ fontSize: 15, lineHeight: 1.75, color: "#4a545e", marginBottom: 16 }}>
                <strong>2.1 License Grant.</strong> Nadir grants Customer a non-exclusive, non-transferable right to access the Services during the Subscription Term, solely for internal business operations.
              </p>
              <p style={{ fontSize: 15, lineHeight: 1.75, color: "#4a545e", marginBottom: 16 }}>
                <strong>2.2 Customer Responsibilities.</strong> Customer is responsible for all activities under its accounts and must ensure compliance with all applicable laws including privacy, data protection, and export control.
              </p>
              <p style={{ fontSize: 15, lineHeight: 1.75, color: "#4a545e" }}>
                <strong>2.3 Usage Restrictions.</strong> Customer shall not: (a) reverse engineer the Services; (b) derive source code or algorithms; (c) build a competitive product; or (d) input unlawful data.
              </p>
            </div>

            {/* Section 3 */}
            <div id="data" style={{ paddingBottom: 48, marginBottom: 48, borderBottom: "1px solid rgba(20,24,28,0.1)" }}>
              <div style={{ fontFamily: MONO, fontSize: 12, color: "#7a848e", letterSpacing: "0.06em", marginBottom: 12 }}>SECTION 03</div>
              <h2 style={{ fontFamily: SERIF, fontWeight: 400, fontSize: 28, margin: "0 0 16px", letterSpacing: "-0.01em", color: "#14181C" }}>Data Ownership and Confidentiality</h2>
              <div style={{ background: "#F6F5F3", borderRadius: 8, padding: "16px 20px", fontSize: 14, lineHeight: 1.7, color: "#4a545e", marginBottom: 20 }}>
                <strong style={{ color: "#14181C" }}>Summary:</strong> Customer retains all ownership of Customer Data. Ontologies, schema maps, and operational graphs generated for Customer are Customer property.
              </div>
              <p style={{ fontSize: 15, lineHeight: 1.75, color: "#4a545e", marginBottom: 16 }}>
                <strong>3.1</strong> Customer grants Nadir a limited license to process Customer Data solely to provide the Services.
              </p>
              <p style={{ fontSize: 15, lineHeight: 1.75, color: "#4a545e", marginBottom: 16 }}>
                <strong>3.2</strong> Resultant Data (ontologies, maps, graphs) are considered Customer Data and remain Customer property upon termination.
              </p>
              <p style={{ fontSize: 15, lineHeight: 1.75, color: "#4a545e" }}>
                <strong>3.3</strong> Both parties agree to protect Confidential Information with reasonable care. All Customer Data, schemas, and workflows are classified as highly Confidential.
              </p>
            </div>

            {/* Section 4 */}
            <div id="warranties" style={{ paddingBottom: 48, marginBottom: 48, borderBottom: "1px solid rgba(20,24,28,0.1)" }}>
              <div style={{ fontFamily: MONO, fontSize: 12, color: "#7a848e", letterSpacing: "0.06em", marginBottom: 12 }}>SECTION 04</div>
              <h2 style={{ fontFamily: SERIF, fontWeight: 400, fontSize: 28, margin: "0 0 16px", letterSpacing: "-0.01em", color: "#14181C" }}>Disclaimer of Warranties</h2>
              <div style={{ background: "#FDF6F0", border: "1px solid rgba(199,69,47,0.15)", borderRadius: 8, padding: "16px 20px", fontSize: 14, lineHeight: 1.7, color: "#4a545e" }}>
                The Services are provided "AS IS." Nadir does not warrant uninterrupted or error-free service. The platform does not guarantee regulatory compliance or prevention of physical incidents. Customer remains solely responsible for its own operational safety and legal compliance.
              </div>
            </div>

            {/* Section 5 */}
            <div id="liability" style={{ paddingBottom: 48 }}>
              <div style={{ fontFamily: MONO, fontSize: 12, color: "#7a848e", letterSpacing: "0.06em", marginBottom: 12 }}>SECTION 05</div>
              <h2 style={{ fontFamily: SERIF, fontWeight: 400, fontSize: 28, margin: "0 0 16px", letterSpacing: "-0.01em", color: "#14181C" }}>Limitation of Liability</h2>
              <p style={{ fontSize: 15, lineHeight: 1.75, color: "#4a545e", marginBottom: 16 }}>
                <strong>5.1</strong> Neither party is liable for indirect, special, incidental, punitive, or consequential damages regardless of legal theory.
              </p>
              <p style={{ fontSize: 15, lineHeight: 1.75, color: "#4a545e" }}>
                <strong>5.2</strong> Total aggregate liability shall not exceed the amounts paid by Customer in the twelve (12) months preceding the incident, except for breaches of confidentiality or indemnification obligations.
              </p>
            </div>
          </div>

          {/* SIDEBAR */}
          <div style={{ position: "sticky", top: 100, alignSelf: "start" }}>
            <div style={{ background: "#F6F5F3", border: "1px solid rgba(20,24,28,0.08)", borderRadius: 12, padding: "24px 20px" }}>
              <div style={{ fontFamily: MONO, fontSize: 12, color: "#7a848e", letterSpacing: "0.06em", marginBottom: 16 }}>ON THIS PAGE</div>
              <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
                {TOC.map((item) => (
                  <a key={item.id} href={`#${item.id}`} style={{ fontSize: 14, color: "#3d4750", textDecoration: "none" }}>{item.label}</a>
                ))}
              </div>
              <div style={{ height: 1, background: "rgba(20,24,28,0.1)", margin: "20px 0" }} />
              <div style={{ fontSize: 13, color: "#7a848e", lineHeight: 1.6 }}>
                Questions? Contact <Link href="/contact" style={{ color: "#0E7C8A", textDecoration: "none" }}>legal@nadir.systems</Link>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* RELATED */}
      <Section alt>
        <div style={{ display: "flex", justifyContent: "center", gap: 24 }}>
          <Link href="/privacy" style={{ fontSize: 15, fontWeight: 600, color: "#0E7C8A", textDecoration: "none" }}>Privacy Policy →</Link>
          <Link href="/security" style={{ fontSize: 15, fontWeight: 600, color: "#0E7C8A", textDecoration: "none" }}>Security & Trust →</Link>
        </div>
      </Section>
    </>
  );
}
